import "./globals.css";
import { JetBrains_Mono } from "next/font/google";

const inter = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jb-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
    </html>
  );
}
